### ISSUE TITLE
As for now, still get any plans to release the code?

### ISSUE THREAD

**Issue by OpenOceanCold** [kennymckormick/Triplet-Representation-of-human-Body#3]
as title

**Comment by OpenOceanCold** [comment]
@kennymckormick

**Comment by kennymckormick** [comment]
Hi, OpenOceanCold,
    The code is originally implemented on an internal version of caffe, so I can't release it without reimplementation. For the directional convolution module, we implement it with several normal convolutions sharing weights + masking.  For the pairwise mapping module, we estimate a 2-channel offset for each joint, and warp the heatmap with [flow_warp_layer](https://github.com/kennymckormick/Triplet-Representation-of-human-Body/files/6059167/flow_warp_layer.cpp.txt) based on the offset. Currently I'm busy with ICCV, maybe I will add the pytorch reimplementation in [mmpose](https://github.com/open-mmlab/mmpose) after the DDL (currently there is a MPII-trb baseline there).

**Comment by OpenOceanCold** [comment]
I see. Thank you！Looking forward to your excelent work!
